# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 397b50a2355d4326c6d6855756bd0e8537a7378b2f3600b96d6ddedb05b2077193049017d1429a0c521578f714fc1ea628f7538762faa4072beeea38e45ed90e

test:
  secret_key_base: 036513c86b57c4f67364ba01684db71be1fe9aaa19e0de1ceab95bd3f79be359b0de22c19f492cd91f97ee4c4dad0a70b629c40f7a0bcae70f07062b1aa1f2be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
